/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/notificationselfservice/clienttest/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger events */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Subscription identifier */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized. The server understood the request, but access is not allowed, i.e. calling user does not have access. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["NoResponse"];
                        "application/json": components["schemas"]["NoResponse"];
                        "text/json": components["schemas"]["NoResponse"];
                    };
                };
                /** @description Not found. There is no resource behind the URL, i.e. requesting a subscription that does not exist. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["NullNotificationSelfServiceErrorResponse"];
                        "application/json": components["schemas"]["NullNotificationSelfServiceErrorResponse"];
                        "text/json": components["schemas"]["NullNotificationSelfServiceErrorResponse"];
                    };
                };
                /** @description Internal Server Error. Something unexpected happened on BC Connect side. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        NoResponse: Record<string, never>;
        /** @enum {string} */
        ErrorCode: "NoError" | "DuplicateEntry" | "InvalidEncryptionKey" | "InvalidStatus" | "InvalidUrl" | "MaxNumberExceeded" | "UnsupportedValue" | "NotFound" | "NotSameTargetType" | "MissingInput";
        NotificationSelfServiceErrorResponse: {
            $type: string;
            errorCode?: components["schemas"]["ErrorCode"];
            errorMessage?: string | null;
        };
        NullNotificationSelfServiceErrorResponse: {
            $type: "NullNotificationSelfServiceErrorResponse";
        } & (Omit<components["schemas"]["NotificationSelfServiceErrorResponse"], "$type"> & Record<string, never>);
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
